### PR TITLE
Smol Slime

### PR DESCRIPTION
**Pull request by ShineBrightMeow**
6-Sided Cal, Screenshots/Videos, how to change board defines, how to use Konfig GUI, LED Error Codes, and debugging with SWD Tools to be added in the future.

### CODE REVIEW

**Comment by Eirenliel** [comment]
I'm not sure smol slime is ready to be this public. The firmware needs a full rewrite, and even the protocol is not finalized.

**Comment by ShineBrightMeow** [comment]
This is true as well, but testers are needed in order to get the firmware to where we want it to be. Features, bug fixes, and etc. A disclaimer can be added to the top of the page (highly experimental).

**Comment by Eirenliel** [comment]
If there is a disclaimer that the slimes might become incompatible with new versions of the server (and will require fw update) and that nothing is final, especially firmare, that's fine.

**Comment by ShineBrightMeow** [comment]
Disclaimer added.

**Review by calliePepper — APPROVED** [review]

**Pull request merged**
