### PR TITLE
Adding Safety Guide

### PR DESCRIPTION
**Pull request by Vyolex**
First off IDK if I did this right.

The goal of this PR is to add a page to the documentation website with the safety information, open to suggestions on how this specifically should be achieved. For now I added them all on a single page as a template/first suggestion.

### CODE REVIEW

**Review by Eirenliel — APPROVED** [review]

**Review by ButterscotchV — COMMENTED** [review]
I think we could also have a warning about having straps too tight cutting circulation? Looks good other than the double period.

**Comment by Vyolex** [comment]
Back to draft to add butter's suggestion and to implement pontoon support.

**Comment by Vyolex** [comment]
@ImUrX could you check pls if I have understood everything correctly? (Feel free to DM fixes that need to be done or just put them here)

**Comment by ButterscotchV** [comment]
The added warning looks good, please re-request a review from me when it's ready.

**Review by ImUrX — APPROVED** [review]

**Review by ButterscotchV — COMMENTED** [review]
This PR is all good aside from not being implemented fully, it's basically just a placeholder page with translation files for now. This is my "somewhat approved" approval, as this isn't really a complete thing.

**Review by Eirenliel — APPROVED** [review]

**Review by calliePepper — APPROVED** [review]

**Comment by calliePepper** [comment]
Is this ok to merge or are you still going at it?

**Comment by Vyolex** [comment]
> Is this ok to merge or are you still going at it?

Unsure, depends on what @ImUrX wants to do and the status of #157.

**Comment by ImUrX** [comment]
Merge it, I will rebase and adapt it to fluent :p

**Pull request merged**
