### PR TITLE
Fix SteamVR trackers trackers toggle section

### PR DESCRIPTION
**Pull request by Louka3000**

### CODE REVIEW

**Comment by Eirenliel** [comment]
Please upload the image to the repo instead of using imgur

**Comment by TheDevMinerTV** [comment]
Please add it as a Git LFS file and not in the actual repo. PNGs are big and don't belong in source control.

**Comment by deiteris** [comment]
> Please add it as a Git LFS file and not as an actual Git file. PNGs are big and don't belong in source control.

Uncompressed PNG size: 11kb
After lossless compression: 3.3kb

Our favicon is larger than this image, lmao. But maybe using Git LFS has some benefits for rarely changed static files.

**Comment by Eirenliel** [comment]
Ideally, all images will be in LFS. It's also better for diff performance. Actually I don't know why they aren't? LFS should've been set up for all repos... It's a bit of a pain to move files to LFS.

**Review by Eirenliel — APPROVED** [review]

**Review by calliePepper — APPROVED** [review]

**Pull request merged**
