### PR TITLE
Update AutoBone documentation and add/update a few entries in "Common Issues"

### PR DESCRIPTION
**Pull request by ButterscotchV**
- Updates AutoBone naming from "Skeleton Auto-Configuration" to "AutoBone / Automatic body proportions calibration".
- Updates AutoBone docs to properly represent the current recommended steps.
- Adds the current visual reference for AutoBone movement calibration steps.
- Updates "The trackers are connected to my WiFi but don't turn up on SlimeVR" to include additional debugging steps to isolate the issue.
- Adds "AutoBone / Automatic body proportions calibration isn't working" to link to the "Common Issues / Debugging" section of the AutoBone documentation.
- Adds "SlimeVR is stuck at "Connecting to the server"" to help with the common problem of having an invalid `vrconfig.yml` file.
- Adds "WebView2 is missing / SlimeVR GUI crashes immediately / "panicked at ... WebView2Error"" to help with the common problem of not having WebView2 installed properly.
- Updates the top of the "Common Issues" page to include links to the Discord support forum and mention to list what you have tried when asking for help.

### CODE REVIEW

**Review by Eirenliel — CHANGES_REQUESTED** [review]

**Review by Vyolex — APPROVED** [review]
Only nitpick-y thing is that the use of Wi-Fi and WiFi is inconsistent, I *think* the correct term here should be WiFi over Wi-Fi.

**Comment by ButterscotchV** [comment]
> Only nitpick-y thing is that the use of Wi-Fi and WiFi is inconsistent, I _think_ the correct term here should be WiFi over Wi-Fi.

I felt this too. The **official** name is "Wi-Fi", but "WiFi" is more commonly used and I think just looks better. The reason I left the inconsistency between Wi-Fi and WiFi was that correcting it would break every link pointing to those headers.

**Comment by ButterscotchV** [comment]
If #156 is merged first, that can be used to improve the headers and fix the consistency issues with "Wi-Fi" vs. "WiFi" and keep the old links to AutoBone docs working while updating the headers

**Comment by ButterscotchV** [comment]
> Only nitpick-y thing is that the use of Wi-Fi and WiFi is inconsistent, I _think_ the correct term here should be WiFi over Wi-Fi.

Should be fixed with my latest commit <3

**Review by Vyolex — COMMENTED** [review]
Any reason there are markdown ids and html ids mixed?

**Comment by ButterscotchV** [comment]
> Any reason there are markdown ids and html ids mixed?

The HTML headers are there in order to have a blank header that can still be targeted, this allows for changing the header but not breaking old links. Please let me know if there's a way to do this through markdown headers, I wasn't able to find any way to do so other than this.

**Review by Vyolex — APPROVED** [review]

**Review by calliePepper — APPROVED** [review]

**Comment by calliePepper** [comment]
We have a few pull requests that are conflicting (mainly common-issues.md), would you mind pulling in the changes if possible?

**Review by Eirenliel — APPROVED** [review]

**Pull request merged**
