### PR TITLE
Added ShadowPC guide based on the original guide written by Blaine

### PR DESCRIPTION
**Pull request by Smeltie**
Added ShadowPC guide based on the original guide written by Blaine over on the discord.

### CODE REVIEW

**Comment by calliePepper** [comment]
The steps should numbered as the list order is important!

**Comment by Smeltie** [comment]
@calliePepper Numbered the steps as requested

**Review by calliePepper — COMMENTED** [review]
and done!

**Review by calliePepper — APPROVED** [review]

**Comment by calliePepper** [comment]
Would you mind double checking my changes?

**Comment by Smeltie** [comment]
> Would you mind double checking my changes?

Seems good! @calliePepper

**Pull request merged**
