### PR TITLE
Give all headers custom IDs and add page titles

### PR DESCRIPTION
**Pull request by ButterscotchV**
This will keep the header ID the same even if we change the wording, this should make it a lot easier to keep old links working while keeping the text up-to-date and high quality. This should also help with supporting translations whenever we may get to that.

This PR also fixes headers on the "SlimeVR on Linux" page.

The header custom IDs were generated for this PR using this Python script: https://gist.github.com/ButterscotchV/0aeba7dbebfba9ad55443ad1b71f5648

### CODE REVIEW

**Review by Eirenliel — APPROVED** [review]

**Comment by Eirenliel** [comment]
Needs rebase :3

**Comment by ButterscotchV** [comment]
Needs https://github.com/rust-lang/mdBook/pull/2013 to be merged (or otherwise have support added for custom header IDs)

**Comment by calliePepper** [comment]
We are just waiting for that mdBook merge right? Just making sure I have nothing to action here (otherwise it looks good)

**Comment by ButterscotchV** [comment]
> We are just waiting for that mdBook merge right? Just making sure I have nothing to action here (otherwise it looks good)

That is correct, it should be all ready for merge once the custom header IDs are supported properly

**Comment by ImUrX** [comment]
it got merged!
will update docs when they make a new release

**Pull request closed without merging**
