### PR TITLE
Use MDBook

### PR DESCRIPTION
**Pull request by ImUrX**
The reasons of the change mainly comes from having easier translations. Even though I haven't found much, this is the best I could get :sob:

### CODE REVIEW

**Comment by ImUrX** [comment]
The site is ready for testing and all in here: https://imurx.github.io/SlimeVR-Docs-Site/

**Comment by Vyolex** [comment]
where did table of contents go 
image
image

**Comment by Vyolex** [comment]
Some weird markdown thingies 
image

**Comment by Vyolex** [comment]
Not sure you can do a lot about this but the table is not adhering to the page size 
image

**Comment by ImUrX** [comment]
The first one, it was auto-generated by Jekyll, now it needs to be written by hand and maybe add descriptions to the table of contents

Second one, I can fix that, will do.

Third one is surely because the table is not actually done on markdown, fixable with css :p

**Comment by calliePepper** [comment]
Seconded really on a lot of this. The table of contents on the parent pages served as a good breakdown of the steps required but it was automated by what we were using. To be honest, having the freedom to build it properly instead of relying on automation is positive.

I like the styling of the tables now, but they do need a little CSS finagling (which is fun).

Overal though, this is a really positive change!

**Comment by calliePepper** [comment]
A couple of notes I'm leaving here from the doc channel on discord:
1. On higher res it needs to expand the width for content and the text size (try to keep similar characters per line)
2. Can we remove / partially remove some of the numbering? Things like setup numerically coming before DIY gives a false impression, but this is even more of a weird situation when you get to Applications and Variants that don't really have an order

**Comment by ImUrX** [comment]
The left table of contents is managed by the SUMMARY.md file, if you have suggestions on how it should be.

**Review by calliePepper — APPROVED** [review]
Kboom time

**Pull request merged**
